server:
  port: 8080

# 数据库配置信息 使用 Druid数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_crud?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: 56789x

# Mybatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
